name: Integration

on:
  push:
    branches: [ main ]  # Only run on pushes to the main branch (adjust as needed)
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  tests:
    name: Integration
    runs-on: ubuntu-latest  # Use the latest available Ubuntu runner for flexibility

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for changes in translation files
        id: changed-translation-files
        run: |
          # Define the paths to check
          paths="src/**/Resources/translations/*.xlf"
          # Use git diff to check if any of the paths have changed
          if git diff --quiet HEAD~1 HEAD -- $paths; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Check Translation Status
        if: steps.changed-translation-files.outputs.changed == 'true'
        run: |
          php src/Symfony/Component/Translation/Resources/bin/translation-status.php -v
