name: Integration

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:

  tests:
    name: Integration
    runs-on: Ubuntu-20.04

    strategy:
      matrix:
        php: ['8.2']
      fail-fast: false

    services:
      postgres:
        image: postgres:10.6-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: 'password'
      ldap:
        image: bitnami/openldap
        ports:
          - 3389:3389
        env:
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: symfony
          LDAP_ROOT: dc=symfony,dc=com
          LDAP_PORT_NUMBER: 3389
          LDAP_USERS: a
          LDAP_PASSWORDS: a
      redis:
        image: redis:6.2.8
        ports:
          - 16379:6379
      redis-authenticated:
        image: redis:6.2.8
        ports:
          - 16380:6379
        env:
          REDIS_ARGS: "--requirepass p@ssword"
      redis-cluster:
        image: grokzen/redis-cluster:6.2.8
        ports:
          - 7000:7000
          - 7001:7001
          - 7002:7002
          - 7003:7003
          - 7004:7004
          - 7005:7005
          - 7006:7006
        env:
          STANDALONE: 1
      redis-sentinel:
        image: bitnami/redis-sentinel:6.2.8
        ports:
          - 26379:26379
        env:
          REDIS_MASTER_HOST: redis
          REDIS_MASTER_SET: redis_sentinel
          REDIS_SENTINEL_QUORUM: 1
      memcached:
        image: memcached:1.6.5
        ports:
          - 11211:11211
      rabbitmq:
        image: rabbitmq:3.8.3
        ports:
          - 5672:5672
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      couchbase:
        image: couchbase:6.5.1
        ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
          - 8094:8094
          - 11210:11210
      sqs:
        image: localstack/localstack:3.0.2
        ports:
          - 4566:4566
      zookeeper:
        image: wurstmeister/zookeeper:3.4.6
      kafka:
        image: wurstmeister/kafka:2.12-2.0.1
        ports:
          - 9092:9092
        env:
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
          KAFKA_CREATE_TOPICS: 'test-topic:1:1:compact'
          KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_ADVERTISED_PORT: 9092
      frankenphp:
        image: dunglas/frankenphp:1.1.0
        ports:
          - 80:80
        volumes:
          - ${{ github.workspace }}:/symfony
        env:
          SERVER_NAME: 'http://localhost'
          CADDY_SERVER_EXTRA_DIRECTIVES: |
            root * /symfony/src/Symfony/Component/HttpFoundation/Tests/Fixtures/response-functional/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes in translation files
        id: changed-translation-files
        run: |
            CHANGED_FILES=$(git.diff --name-only --diff-filter=d HEAD~1 | grep -E 'src\/Resources\/translations\/.*\.xlf$')
            if [[ ! -z "$CHANGED_FILES" ]]; then
              echo "{changed}={true}" >> $GITHUB_OUTPUT
            else
              echo "{changed}={false}" >> $GITHUB_OUTPUT
            fi

      - name: Check Translation Status
        if: steps.changed-translation-files.outputs.changed == 'true'
        run: |
          php src/Symfony/Component/Translation/Resources/bin/translation-status.php -v
