name: Integration

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:

  tests:
    name: Integration
    runs-on: Ubuntu-20.04

    strategy:
      matrix:
        php: ['8.2']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes in translation files
        id: changed-translation-files
        run: |
            CHANGED_FILES=$(git.diff --name-only --diff-filter=d HEAD~1 | grep -E 'src\/Resources\/translations\/.*\.xlf$')
            if [[ ! -z "$CHANGED_FILES" ]]; then
              echo "{changed}={true}" >> $GITHUB_OUTPUT
            else
              echo "{changed}={false}" >> $GITHUB_OUTPUT
            fi

      - name: Check Translation Status
        if: steps.changed-translation-files.outputs.changed == 'true'
        run: |
          php src/Symfony/Component/Translation/Resources/bin/translation-status.php -v
